FROM nginx:24-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

RUN npm run build

# Stage 2: Serve the app with nginx
FROM nginx:24-alpine 

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./

RUN npm install serve

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]